Rumus Volume
V = N × log2(n)

In [7]:
import pandas as pd

df = pd.read_csv('halstead_defensible.csv')
df.head()

,file,N1,N2,n1,n2,length,vocabulary,volume,difficulty,effort,bugs
0,ExampleInstrumentedTest.kt,18,37,4,33,55,37,286.52,2.24,642.50,0.0955
1,AgrimateApplication.kt,1,2,1,2,3,3,4.75,0.50,2.38,0.0016
2,BaseViewModel.kt,4,19,2,15,23,17,94.01,1.27,119.08,0.0313
3,FormHandler.kt,2,5,1,5,7,6,18.09,0.50,9.05,0.0060
4,AppModule.kt,22,53,1,43,75,44,409.46,0.62,252.34,0.1365

In [8]:
# ubah nama kolom 'file_name' menjadi 'Nama Kelas'
df = df.rename(columns={'file': 'Nama Kelas'})

# ubah nama kolom 'halstead_volume' menjadi 'Halstead Volume'
df = df.rename(columns={'volume': 'V'})

# kolom menjadi dua hanya 'Nama Kelas' dan 'Halstead Volume'
df = df[['Nama Kelas', 'V']]

In [9]:
df.head()

                   Nama Kelas       V
0  ExampleInstrumentedTest.kt  286.52
1      AgrimateApplication.kt    4.75
2            BaseViewModel.kt   94.01
3              FormHandler.kt   18.09
4                AppModule.kt  409.46

In [10]:
# hapus nama kelas yang tidak ada 'ExampleInstrumentedTest.kt', 'ExampleUnitTest.kt', 'FormatUtilsTest.kt', 'DateUtilsTest.kt'
df = df[~df['Nama Kelas'].isin(['ExampleInstrumentedTest.kt', 'ExampleUnitTest.kt', 'FormatUtilsTest.kt', 'DateUtilsTest.kt'])]
df.head()

               Nama Kelas       V
1  AgrimateApplication.kt    4.75
2        BaseViewModel.kt   94.01
3          FormHandler.kt   18.09
4            AppModule.kt  409.46
5        LibraryModule.kt   55.35

In [11]:
# import menjadi export ke excel
df.to_excel('halstead_core_result_analysis.xlsx', index=False)