In [1]:
import pandas as pd

dfCC = pd.read_csv('../cc/cc_per_file.csv')
dfCC.head()

,file_name,file_path,cyclomatic_complexity
0,ExampleInstrumentedTest.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1
1,AgrimateApplication.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1
2,BaseViewModel.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1
3,FormHandler.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1
4,AppModule.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,1

In [2]:
# hapus kolom file_path
dfCC = dfCC.drop(columns=['file_path'])

# ubah nama kolom 'file_name' menjadi 'Nama Kelas'
dfCC = dfCC.rename(columns={'file_name': 'Nama Kelas'})

# ubah nama kolom 'cyclomatic_complexity' menjadi 'V(g)'
dfCC = dfCC.rename(columns={'cyclomatic_complexity': 'V(g)'})

In [3]:
dfCC.head()

                   Nama Kelas  V(g)
0  ExampleInstrumentedTest.kt     1
1      AgrimateApplication.kt     1
2            BaseViewModel.kt     1
3              FormHandler.kt     1
4                AppModule.kt     1

In [4]:
dfCLOC_app = pd.read_csv('../cloc/cloc_app_result.csv')
dfCLOC_core = pd.read_csv('../cloc/cloc_core_result.csv')
dfCLOC_app.head()

,file_name,file_path,cloc
0,AgrimateApplication.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0
1,BaseViewModel.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0
2,FormHandler.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0
3,AppModule.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0
4,LibraryModule.kt,C:\Users\dewat\Desktop\Project Skripsi Agrimat...,0

In [5]:
# hapus kolom file_path
dfCLOC_app = dfCLOC_app.drop(columns=['file_path'])
dfCLOC_core = dfCLOC_core.drop(columns=['file_path'])

# ubah nama kolom 'file_name' menjadi 'Nama Kelas'
dfCLOC_app = dfCLOC_app.rename(columns={'file_name': 'Nama Kelas'})
dfCLOC_core = dfCLOC_core.rename(columns={'file_name': 'Nama Kelas'})

# ubah nama kolom 'cyclomatic_complexity' menjadi 'V(g)'
dfCLOC_app = dfCLOC_app.rename(columns={'cloc': 'CLOC'})
dfCLOC_core = dfCLOC_core.rename(columns={'cloc': 'CLOC'})

In [6]:
dfCLOC_app.head()

               Nama Kelas  CLOC
0  AgrimateApplication.kt     0
1        BaseViewModel.kt     0
2          FormHandler.kt     0
3            AppModule.kt     0
4        LibraryModule.kt     0

In [7]:
dfCLOC_core.head()

                    Nama Kelas  CLOC
0        AuthRepositoryImpl.kt     0
1   CommodityRepositoryImpl.kt     0
2   DataStoreRepositoryImpl.kt     0
3  FarmerLandRepositoryImpl.kt     0
4     HarvestRepositoryImpl.kt     0

In [8]:
# gabung dataframe dfCLOC_app dengan dfCLOC_core
dfCLOC = pd.concat([dfCLOC_app, dfCLOC_core], ignore_index=True)
dfCLOC.head()

               Nama Kelas  CLOC
0  AgrimateApplication.kt     0
1        BaseViewModel.kt     0
2          FormHandler.kt     0
3            AppModule.kt     0
4        LibraryModule.kt     0

In [9]:
# ada berapa kelas yang ada di dfCC tapi tidak ada di dfCLOC
dfCC_names = set(dfCC['Nama Kelas'])
dfCLOC_names = set(dfCLOC['Nama Kelas'])
missing_in_cloc = dfCC_names - dfCLOC_names
print(f"Kelas yang ada di dfCC tapi tidak ada di dfCLOC: {missing_in_cloc}")

Kelas yang ada di dfCC tapi tidak ada di dfCLOC: {'ExampleUnitTest.kt', 'DateUtilsTest.kt', 'ExampleInstrumentedTest.kt', 'FormatUtilsTest.kt'}

In [10]:
# hapus nama kelas yang tidak ada di dfCLOC dari dfCC
dfCC = dfCC[dfCC['Nama Kelas'].isin(dfCLOC_names)]
dfCC.head()

               Nama Kelas  V(g)
1  AgrimateApplication.kt     1
2        BaseViewModel.kt     1
3          FormHandler.kt     1
4            AppModule.kt     1
5        LibraryModule.kt     1

In [11]:
# ada berapa kelas yang ada di dfCC tapi tidak ada di dfCLOC
dfCC_names = set(dfCC['Nama Kelas'])
dfCLOC_names = set(dfCLOC['Nama Kelas'])
missing_in_cloc = dfCC_names - dfCLOC_names
print(f"Kelas yang ada di dfCC tapi tidak ada di dfCLOC: {missing_in_cloc}")

Kelas yang ada di dfCC tapi tidak ada di dfCLOC: set()

In [12]:
dfHL = pd.read_csv('../hl/halstead_defensible.csv')
dfHL.head()

,file,N1,N2,n1,n2,length,vocabulary,volume,difficulty,effort,bugs
0,ExampleInstrumentedTest.kt,18,37,4,33,55,37,286.52,2.24,642.50,0.0955
1,AgrimateApplication.kt,1,2,1,2,3,3,4.75,0.50,2.38,0.0016
2,BaseViewModel.kt,4,19,2,15,23,17,94.01,1.27,119.08,0.0313
3,FormHandler.kt,2,5,1,5,7,6,18.09,0.50,9.05,0.0060
4,AppModule.kt,22,53,1,43,75,44,409.46,0.62,252.34,0.1365

In [13]:
# hapus kolom kecuali file dan volume
dfHL = dfHL[['file', 'volume']]

# ubah nama kolom 'file' menjadi 'Nama Kelas'
dfHL = dfHL.rename(columns={'file': 'Nama Kelas'})

# ubah nama kolom 'volume' menjadi 'HL(V)'
dfHL = dfHL.rename(columns={'volume': 'HL(V)'})

dfHL.head()

                   Nama Kelas   HL(V)
0  ExampleInstrumentedTest.kt  286.52
1      AgrimateApplication.kt    4.75
2            BaseViewModel.kt   94.01
3              FormHandler.kt   18.09
4                AppModule.kt  409.46

In [14]:
# hapus nama kelas yang tidak ada di dfCLOC dari dfCC
dfHL = dfHL[dfHL['Nama Kelas'].isin(dfCLOC_names)]
dfHL.head()

               Nama Kelas   HL(V)
1  AgrimateApplication.kt    4.75
2        BaseViewModel.kt   94.01
3          FormHandler.kt   18.09
4            AppModule.kt  409.46
5        LibraryModule.kt   55.35

In [15]:
dfLOC = pd.read_csv('../loc/loc_mi.csv')
dfLOC.head()

                         file  loc_mi
0  ExampleInstrumentedTest.kt      14
1      AgrimateApplication.kt       5
2            BaseViewModel.kt      15
3              FormHandler.kt       5
4                AppModule.kt      60

In [16]:
# ubah nama kolom 'file_name' menjadi 'Nama Kelas'
dfLOC = dfLOC.rename(columns={'file': 'Nama Kelas'})

# ubah nama kolom 'loc' menjadi 'LOC'
dfLOC = dfLOC.rename(columns={'loc_mi': 'LOC'})

In [17]:
dfLOC.head()

                   Nama Kelas  LOC
0  ExampleInstrumentedTest.kt   14
1      AgrimateApplication.kt    5
2            BaseViewModel.kt   15
3              FormHandler.kt    5
4                AppModule.kt   60

In [18]:
# hapus nama kelas yang tidak ada di dfCLOC dari dfCC
dfLOC = dfLOC[dfLOC['Nama Kelas'].isin(dfCLOC_names)]
dfLOC.head()

               Nama Kelas  LOC
1  AgrimateApplication.kt    5
2        BaseViewModel.kt   15
3          FormHandler.kt    5
4            AppModule.kt   60
5        LibraryModule.kt   19

In [19]:
import math

def calculate_mi(cc, hl, loc, cloc):
    """
    cc   : Cyclomatic Complexity
    hl   : Halstead Volume
    loc  : Lines of Code
    cloc : Comment Lines of Code
    """

    # hindari error log(0)
    if loc == 0 or hl == 0:
        return 0

    # percent comment
    per_cm = (cloc / loc) * 100

    mi = (
        171
        - 5.2 * math.log(hl)
        - 0.23 * cc
        - 16.2 * math.log(loc)
        + 50 * math.sin(math.sqrt(2.46 * per_cm))
    )

    return round(mi, 2)

In [20]:
cc = 12
hl = 350.7
loc = 220
cloc = 40

mi = calculate_mi(cc, hl, loc, cloc)
print("Maintainability Index:", mi)

Maintainability Index: 70.08

In [21]:
# gabung semua dataframe berdasarkan 'Nama Kelas' dari data frame dfCC, dfHL, dfLOC, dfCLOC
df_merged = dfCC.merge(dfHL, on='Nama Kelas').merge(dfLOC, on='Nama Kelas').merge(dfCLOC, on='Nama Kelas')

df_merged.head()

               Nama Kelas  V(g)   HL(V)  LOC  CLOC
0  AgrimateApplication.kt     1    4.75    5     0
1        BaseViewModel.kt     1   94.01   15     0
2          FormHandler.kt     1   18.09    5     0
3            AppModule.kt     1  409.46   60     0
4        LibraryModule.kt     1   55.35   19     0

In [22]:
# calculate MI for each row and store it in a new column 'MI'
df_merged['MI'] = df_merged.apply(lambda row: calculate_mi(row['V(g)'], row['HL(V)'], row['LOC'], row['CLOC']), axis=1)

In [23]:
df_merged.head()

               Nama Kelas  V(g)   HL(V)  LOC  CLOC      MI
0  AgrimateApplication.kt     1    4.75    5     0  136.59
1        BaseViewModel.kt     1   94.01   15     0  103.27
2          FormHandler.kt     1   18.09    5     0  129.64
3            AppModule.kt     1  409.46   60     0   73.16
4        LibraryModule.kt     1   55.35   19     0  102.20

In [24]:
# def classify_mi(mi):
#     if 0 <= mi <= 9:
#         return "Tough to Maintain"
#     elif 10 <= mi <= 19:
#         return "Moderate Level of Difficulty to Maintain"
#     elif 20 <= mi <= 100:
#         return "Easy to Maintain"
#     else:
#         return "Out of Range"

def classify_mi(mi):
    if mi > 85:
        return "Highly Maintainable"
    elif mi > 65:
        return "Moderately Maintainable"
    else:
        return "Difficult to Maintain"

In [25]:
# buat kolom baru 'Maintainability Level' berdasarkan nilai MI
df_merged['Maintainability Level'] = df_merged['MI'].apply(classify_mi)

In [26]:
df_merged

,Nama Kelas,V(g),HL(V),LOC,CLOC,MI,Maintainability Level
0,AgrimateApplication.kt,1,4.75,5,0,136.59,Highly Maintainable
1,BaseViewModel.kt,1,94.01,15,0,103.27,Highly Maintainable
2,FormHandler.kt,1,18.09,5,0,129.64,Highly Maintainable
3,AppModule.kt,1,409.46,60,0,73.16,Moderately Maintainable
4,LibraryModule.kt,1,55.35,19,0,102.20,Highly Maintainable
...,...,...,...,...,...,...,...
290,AuthInterceptor.kt,1,171.82,19,0,96.31,Highly Maintainable
291,ErrorUtils.kt,3,513.19,29,0,83.31,Moderately Maintainable
292,Mapper.kt,1,23.26,4,0,131.95,Highly Maintainable
293,RequestFlow.kt,5,505.58,32,0,81.33,Moderately Maintainable
294,Resource.kt,1,132.88,6,0,116.32,Highly Maintainable

In [27]:
# coba ada berapa kelas yang termasuk dalam setiap kategori maintainability level
df_merged['Maintainability Level'].value_counts()

Maintainability Level
Highly Maintainable        162
Difficult to Maintain       73
Moderately Maintainable     60
Name: count, dtype: int64

In [28]:
df_merged

,Nama Kelas,V(g),HL(V),LOC,CLOC,MI,Maintainability Level
0,AgrimateApplication.kt,1,4.75,5,0,136.59,Highly Maintainable
1,BaseViewModel.kt,1,94.01,15,0,103.27,Highly Maintainable
2,FormHandler.kt,1,18.09,5,0,129.64,Highly Maintainable
3,AppModule.kt,1,409.46,60,0,73.16,Moderately Maintainable
4,LibraryModule.kt,1,55.35,19,0,102.20,Highly Maintainable
...,...,...,...,...,...,...,...
290,AuthInterceptor.kt,1,171.82,19,0,96.31,Highly Maintainable
291,ErrorUtils.kt,3,513.19,29,0,83.31,Moderately Maintainable
292,Mapper.kt,1,23.26,4,0,131.95,Highly Maintainable
293,RequestFlow.kt,5,505.58,32,0,81.33,Moderately Maintainable
294,Resource.kt,1,132.88,6,0,116.32,Highly Maintainable

In [29]:
# filter dari atas ke bawah maintainability level dari highly, moderate, difficult
df_merged = df_merged.sort_values(by='Maintainability Level', key=lambda x: x.map({'Highly Maintainable': 0, 'Moderately Maintainable': 1, 'Difficult to Maintain': 2}))

In [30]:
df_merged

,Nama Kelas,V(g),HL(V),LOC,CLOC,MI,Maintainability Level
287,SignUpMapper.kt,1,101.58,14,0,103.99,Highly Maintainable
286,SignInMapper.kt,1,138.97,16,0,100.20,Highly Maintainable
285,RemainingLandAreaMapper.kt,1,95.18,15,0,103.21,Highly Maintainable
284,RegionMapper.kt,1,91.38,13,0,105.74,Highly Maintainable
0,AgrimateApplication.kt,1,4.75,5,0,136.59,Highly Maintainable
...,...,...,...,...,...,...,...
46,CheckDiseaseScreen.kt,10,5703.48,338,12,38.65,Difficult to Maintain
45,NotificationScreen.kt,3,1008.95,112,0,57.90,Difficult to Maintain
29,LandReportAddScreen.kt,1,1497.93,116,0,55.74,Difficult to Maintain
31,LandDetailScreen.kt,12,5635.18,344,0,28.71,Difficult to Maintain
7,ChatScreen.kt,1,1285.14,100,0,58.94,Difficult to Maintain

In [31]:
# maintability level highly, moderate, difficult ada berapa masing-masing
df_merged['Maintainability Level'].value_counts()

Maintainability Level
Highly Maintainable        162
Difficult to Maintain       73
Moderately Maintainable     60
Name: count, dtype: int64

In [32]:
# export df_merged to excel
#df_merged.to_excel('maintainability_index_analysis.xlsx', index=False)

In [33]:
df_merged.to_csv('maintainability_index_analysis.csv', index=False)