In [12]:
import pandas as pd

df = pd.read_csv('loc_mi.csv')
df.head()

                         file  loc_mi
0  ExampleInstrumentedTest.kt      14
1      AgrimateApplication.kt       5
2            BaseViewModel.kt      15
3              FormHandler.kt       5
4                AppModule.kt      60

In [13]:
# ubah nama file_name menjadi Nama Kelas
df = df.rename(columns={'file': 'Nama Kelas'})

# ubah nama kolom logical_loc menjadi LOC
df = df.rename(columns={'loc_mi': 'LOC'})

In [14]:
df.head()

                   Nama Kelas  LOC
0  ExampleInstrumentedTest.kt   14
1      AgrimateApplication.kt    5
2            BaseViewModel.kt   15
3              FormHandler.kt    5
4                AppModule.kt   60

In [15]:
# hapus nama kelas yang tidak ada 'ExampleInstrumentedTest.kt', 'ExampleUnitTest.kt', 'FormatUtilsTest.kt', 'DateUtilsTest.kt'
df = df[~df['Nama Kelas'].isin(['ExampleInstrumentedTest.kt', 'ExampleUnitTest.kt', 'FormatUtilsTest.kt', 'DateUtilsTest.kt'])]
df.head()

               Nama Kelas  LOC
1  AgrimateApplication.kt    5
2        BaseViewModel.kt   15
3          FormHandler.kt    5
4            AppModule.kt   60
5        LibraryModule.kt   19

In [16]:
# export ke excel
df.to_excel('loc_core_result_analysis.xlsx', index=False)